apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mtdrworkshop
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mtdrworkshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: react-app
        image: %DOCKER_REGISTRY%/talos-frontend:%IMAGE_VERSION%
        ports:
        - containerPort: 80
---