import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Search, ListIcon, LayoutGrid, Plus } from 'lucide-react';
import { WORK_ITEM_STATUSES } from '../../enums/work-item-status.enum';
import { formatStatusLabel } from '../../lib/dashboard-ui';
export function DashboardToolbar({ search, onSearchChange, statusFilter, onStatusFilterChange, assigneeFilter, onAssigneeFilterChange, viewMode, onViewModeChange, onCreateClick, users, }) {
    return (_jsxs("div", { className: "flex flex-wrap items-center gap-3", children: [_jsxs("div", { className: "relative min-w-[200px] flex-1", children: [_jsx(Search, { className: "pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-400 dark:text-zinc-500" }), _jsx("input", { type: "text", placeholder: "Search tasks\u2026", value: search, onChange: (e) => onSearchChange(e.target.value), className: "w-full rounded-xl border border-zinc-200 bg-white py-2 pl-9 pr-4 text-sm text-zinc-800 placeholder-zinc-400 outline-none focus:border-sky-400/60 focus:ring-1 focus:ring-sky-400/30 dark:border-zinc-700/60 dark:bg-zinc-800/60 dark:text-zinc-200 dark:placeholder-zinc-500 dark:focus:border-sky-500/60 dark:focus:ring-sky-500/30" })] }), _jsxs("select", { value: statusFilter, onChange: (e) => onStatusFilterChange(e.target.value), className: "rounded-xl border border-zinc-200 bg-white px-3 py-2 text-sm text-zinc-700 outline-none focus:border-sky-400/60 focus:ring-1 focus:ring-sky-400/30 dark:border-zinc-700/60 dark:bg-zinc-800/60 dark:text-zinc-300 dark:focus:border-sky-500/60 dark:focus:ring-sky-500/30", children: [_jsx("option", { value: "", children: "All statuses" }), WORK_ITEM_STATUSES.map((s) => (_jsx("option", { value: s, children: formatStatusLabel(s) }, s)))] }), _jsxs("select", { value: assigneeFilter, onChange: (e) => onAssigneeFilterChange(e.target.value), className: "rounded-xl border border-zinc-200 bg-white px-3 py-2 text-sm text-zinc-700 outline-none focus:border-sky-400/60 focus:ring-1 focus:ring-sky-400/30 dark:border-zinc-700/60 dark:bg-zinc-800/60 dark:text-zinc-300 dark:focus:border-sky-500/60 dark:focus:ring-sky-500/30", children: [_jsx("option", { value: "", children: "All assignees" }), users.map((u) => (_jsx("option", { value: u.userId, children: u.name }, u.userId)))] }), _jsxs("div", { className: "flex items-center rounded-xl border border-zinc-200 bg-zinc-100 p-1 dark:border-zinc-700/60 dark:bg-zinc-800/60", children: [_jsxs("button", { type: "button", onClick: () => onViewModeChange('list'), className: `flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-sm font-medium transition-colors ${viewMode === 'list'
                            ? 'bg-white text-zinc-800 shadow-sm dark:bg-zinc-700 dark:text-white dark:shadow-none'
                            : 'text-zinc-500 hover:text-zinc-700 dark:text-zinc-400 dark:hover:text-zinc-200'}`, title: "List view", children: [_jsx(ListIcon, { className: "h-4 w-4" }), _jsx("span", { children: "List" })] }), _jsxs("button", { type: "button", onClick: () => onViewModeChange('kanban'), className: `flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-sm font-medium transition-colors ${viewMode === 'kanban'
                            ? 'bg-white text-zinc-800 shadow-sm dark:bg-zinc-700 dark:text-white dark:shadow-none'
                            : 'text-zinc-500 hover:text-zinc-700 dark:text-zinc-400 dark:hover:text-zinc-200'}`, title: "Kanban view", children: [_jsx(LayoutGrid, { className: "h-4 w-4" }), _jsx("span", { children: "Kanban" })] })] }), _jsxs("button", { type: "button", onClick: onCreateClick, className: "ml-auto flex items-center gap-2 rounded-xl bg-sky-500 px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-sky-600 focus:outline-none focus:ring-2 focus:ring-sky-500/50 dark:hover:bg-sky-400", children: [_jsx(Plus, { className: "h-4 w-4" }), "New Task"] })] }));
}
