spring.jpa.database-platform=org.hibernate.community.dialect.Oracle12cDialect
#oracle.jdbc.fanEnabled=false
##this is not used when deployed in kubernetes. Just for local testing
spring.datasource.url=${DB_URL:jdbc:oracle:thin:@chatbotbd_medium?TNS_ADMIN=${TNS_ADMIN}}
spring.datasource.username=${DB_USERNAME:CHATBOT_USER}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

##Properties of UCP
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
spring.datasource.oracleucp.sql-for-validate-connection=select * from dual
spring.datasource.oracleucp.connection-pool-name=connectionPoolName1
spring.datasource.oracleucp.initial-pool-size=15
spring.datasource.oracleucp.min-pool-size=10
spring.datasource.oracleucp.max-pool-size=30

##Logging properties for UCP
logging.level.root=${LOG_LEVEL:info}
logging.file.name=logs.log
logging.level.oracle.ucp=trace
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type=TRACE

deepseek.api.key=${DEEPSEEK_API_KEY:sk-test}
deepseek.api.url=https://api.deepseek.com/v1/chat/completions

#spring.security.user.name=psong
#spring.security.user.password=WELcome__12345

telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
telegram.bot.name=${TELEGRAM_BOT_NAME:local_test_bot}


