package com.springboot.MyTodoList.controller;

import com.springboot.MyTodoList.dto.search.SemanticSearchRequest;
import com.springboot.MyTodoList.dto.search.SemanticSearchResultList;
import com.springboot.MyTodoList.service.SemanticSearchService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * REST controller for RF-005: Semantic Task Search.
 *
 * Provides an endpoint for natural-language-based task search using
 * vector embeddings generated by Alibaba Cloud DashScope (Qwen).
 *
 * @apiNote POST /api/semantic-search
 */
@RestController
@RequestMapping("/api/semantic-search")
@Tag(name = "Semantic Search", description = "AI-assisted semantic search over work items.")
public class SemanticSearchController {
    private static final Logger log = LoggerFactory.getLogger(SemanticSearchController.class);

    private final SemanticSearchService searchService;

    public SemanticSearchController(SemanticSearchService searchService) {
        this.searchService = searchService;
    }

    /**
     * Performs a semantic search for work items matching the given query.
     *
     * The search uses AI-generated vector embeddings for semantic matching.
     * If the AI service is unavailable, it automatically falls back to
     * keyword-based search and indicates this in the response.
     *
     * @param request the search request containing the query and optional maxResults
     * @return a list of work items ranked by semantic relevance
     */
    @PostMapping
    @Operation(summary = "Search work items semantically", description = "Searches work items by natural-language meaning and falls back to keyword search when AI is unavailable.")
    public ResponseEntity<SemanticSearchResultList> search(
            @Valid @RequestBody SemanticSearchRequest request
    ) {
        log.info("Semantic search request: query='{}', maxResults={}",
                request.getQuery(), request.getMaxResults());

        int maxResults = request.getMaxResults() != null ? request.getMaxResults() : 10;
        SemanticSearchResultList results = searchService.search(request.getQuery(), maxResults);

        return ResponseEntity.ok(results);
    }

    /**
     * Triggers a manual re-index of all work items.
     * Useful for admin operations after bulk data changes.
     *
     * @apiNote POST /api/semantic-search/reindex
     */
    @PostMapping("/reindex")
    @Operation(summary = "Rebuild semantic search index", description = "Re-indexes all work items for semantic search.")
    public ResponseEntity<String> reindex() {
        log.info("Manual re-index triggered");
        searchService.buildIndex();
        return ResponseEntity.ok("Re-indexing complete");
    }
}
