name: Build and publish backend

on:
  push:
    branches: [ "cicd-setup" ]
  pull_request:
    branches: [ "cicd-setup" ]
    paths: ["MtdrSpring/backend/src/main/java/**"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.OCI_REGION }}
        username: ${{ vars.OCI_USERNAME }}
        password: ${{ secrets.OCI_TOKEN }}

    - name: Build the Docker image
      working-directory: MtdrSpring/backend
      run: |
        export IMAGE_NAME=todolistapp-springboot
        export IMAGE_VERSION=0.1
        export DOCKER_REGISTRY=${{ vars.OCI_REGION }}/${{ vars.OCI_TENANCY_NAMESPACE }}/${{ vars.OCI_CONTAINER_REGISTRY }}
        export IMAGE=${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}
        
        mvn clean package spring-boot:repackage
        ls target
        docker build -f Dockerfile -t $IMAGE .
        docker push $IMAGE
        
        
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_BOT_NAME: ${{ vars.TELEGRAM_BOT_NAME }}
        DB_URL: ${{ vars.DB_URL }}
        DB_USERNAME: ${{ vars.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    
    - name: Debug file system
      working-directory: MtdrSpring/backend
      run: ls -R
        
